yay -S --noconfirm adw-gtk-theme-git
yay -S --noconfirm alacritty
yay -S --noconfirm apt
yay -S --noconfirm base
yay -S --noconfirm base-devel
yay -S --noconfirm bat
yay -S --noconfirm bibata-cursor-theme-bin
yay -S --noconfirm blueman
yay -S --noconfirm bluez
yay -S --noconfirm bluez-utils
yay -S --noconfirm breeze-plus
yay -S --noconfirm btop
yay -S --noconfirm capitaine-cursors
yay -S --noconfirm cbonsai
yay -S --noconfirm cliwt
yay -S --noconfirm cmatrix
yay -S --noconfirm cpio
yay -S --noconfirm darkly-bin
yay -S --noconfirm dgop
yay -S --noconfirm dms-shell-bin
yay -S --noconfirm dms-shell-bin-debug
yay -S --noconfirm dosfstools
yay -S --noconfirm efibootmgr
yay -S --noconfirm epub-reader
yay -S --noconfirm fastfetch
yay -S --noconfirm firefox
yay -S --noconfirm flatpak
yay -S --noconfirm git
yay -S --noconfirm google-breakpad
yay -S --noconfirm grub
yay -S --noconfirm gst-plugin-pipewire
yay -S --noconfirm gtk-engine-murrine
yay -S --noconfirm gum
yay -S --noconfirm hyprpaper
yay -S --noconfirm inetutils
yay -S --noconfirm intel-media-driver
yay -S --noconfirm intel-ucode
yay -S --noconfirm iwd
yay -S --noconfirm kamera
yay -S --noconfirm kde-gtk-config
yay -S --noconfirm kvantum
yay -S --noconfirm libpulse
yay -S --noconfirm libva-intel-driver
yay -S --noconfirm linux
yay -S --noconfirm linux-firmware
yay -S --noconfirm localsend-bin
yay -S --noconfirm mariadb
yay -S --noconfirm mate-polkit
yay -S --noconfirm matugen-bin
yay -S --noconfirm meson
yay -S --noconfirm mission-center
yay -S --noconfirm mpd
yay -S --noconfirm mtools
yay -S --noconfirm nano
yay -S --noconfirm nautilus
yay -S --noconfirm neofetch
yay -S --noconfirm neovim
yay -S --noconfirm network-manager-applet
yay -S --noconfirm niri
yay -S --noconfirm nwg-look
yay -S --noconfirm oh-my-posh
yay -S --noconfirm os-prober
yay -S --noconfirm otf-space-grotesk
yay -S --noconfirm pipewire
yay -S --noconfirm pipewire-alsa
yay -S --noconfirm pipewire-jack
yay -S --noconfirm pipewire-pulse
yay -S --noconfirm plasma-browser-integration
yay -S --noconfirm plymouth
yay -S --noconfirm plymouth-theme-cubes-git
yay -S --noconfirm pokemon-colorscripts-git
yay -S --noconfirm pyright
yay -S --noconfirm python-evdev
yay -S --noconfirm python-loguru
yay -S --noconfirm python-pip
yay -S --noconfirm python-pipx
yay -S --noconfirm python-pynvim
yay -S --noconfirm python-pywal16
yay -S --noconfirm python-pywalfox
yay -S --noconfirm python311
yay -S --noconfirm qt6-avif-image-plugin
yay -S --noconfirm qt6-multimedia-ffmpeg
yay -S --noconfirm qt6ct
yay -S --noconfirm rmpc
yay -S --noconfirm rofi
yay -S --noconfirm sassc
yay -S --noconfirm sddm
yay -S --noconfirm sddm-silent-theme
yay -S --noconfirm smartmontools
yay -S --noconfirm sof-firmware
yay -S --noconfirm speech-dispatcher
yay -S --noconfirm spotify-launcher
yay -S --noconfirm stow
yay -S --noconfirm swayidle
yay -S --noconfirm swaync
yay -S --noconfirm swww
yay -S --noconfirm sxiv
yay -S --noconfirm timidity++
yay -S --noconfirm ttf-dejavu
yay -S --noconfirm ttf-fira-code
yay -S --noconfirm ttf-fira-sans
yay -S --noconfirm ttf-firacode-nerd
yay -S --noconfirm ttf-liberation
yay -S --noconfirm ttf-nerd-fonts-symbols
yay -S --noconfirm ttf-rubik-vf
yay -S --noconfirm ttf-twemoji
yay -S --noconfirm tty-clock
yay -S --noconfirm unzip
yay -S --noconfirm uwsm
yay -S --noconfirm vencord-bin
yay -S --noconfirm vim
yay -S --noconfirm vulkan-intel
yay -S --noconfirm vulkan-nouveau
yay -S --noconfirm vulkan-radeon
yay -S --noconfirm waybar
yay -S --noconfirm whitesur-icon-theme-git
yay -S --noconfirm wireless_tools
yay -S --noconfirm woff2-font-awesome
yay -S --noconfirm wofi
yay -S --noconfirm xdg-desktop-portal-gnome
yay -S --noconfirm xdg-utils
yay -S --noconfirm xf86-video-amdgpu
yay -S --noconfirm xf86-video-ati
yay -S --noconfirm xf86-video-nouveau
yay -S --noconfirm xorg-server
yay -S --noconfirm xorg-xinit
yay -S --noconfirm xwayland-satellite
yay -S --noconfirm yay
yay -S --noconfirm yt-x
yay -S --noconfirm zen-browser-bin
yay -S --noconfirm zoxide
yay -S --noconfirm zram-generator
yay -S --noconfirm zsh
yay -S --noconfirm zsh-autosuggestions
yay -S --noconfirm zsh-completions
yay -S --noconfirm zsh-syntax-highlighting
