pacman -S --noconfirm adw-gtk-theme-git
pacman -S --noconfirm alacritty
pacman -S --noconfirm apt
pacman -S --noconfirm base
pacman -S --noconfirm base-devel
pacman -S --noconfirm bat
pacman -S --noconfirm bibata-cursor-theme-bin
pacman -S --noconfirm blueman
pacman -S --noconfirm bluez
pacman -S --noconfirm bluez-utils
pacman -S --noconfirm breeze-plus
pacman -S --noconfirm btop
pacman -S --noconfirm capitaine-cursors
pacman -S --noconfirm cbonsai
pacman -S --noconfirm cliwt
pacman -S --noconfirm cmatrix
pacman -S --noconfirm cpio
pacman -S --noconfirm darkly-bin
pacman -S --noconfirm dgop
pacman -S --noconfirm dms-shell-bin
pacman -S --noconfirm dms-shell-bin-debug
pacman -S --noconfirm dosfstools
pacman -S --noconfirm efibootmgr
pacman -S --noconfirm epub-reader
pacman -S --noconfirm fastfetch
pacman -S --noconfirm firefox
pacman -S --noconfirm flatpak
pacman -S --noconfirm git
pacman -S --noconfirm google-breakpad
pacman -S --noconfirm grub
pacman -S --noconfirm gst-plugin-pipewire
pacman -S --noconfirm gtk-engine-murrine
pacman -S --noconfirm gum
pacman -S --noconfirm hyprpaper
pacman -S --noconfirm inetutils
pacman -S --noconfirm intel-media-driver
pacman -S --noconfirm intel-ucode
pacman -S --noconfirm iwd
pacman -S --noconfirm kamera
pacman -S --noconfirm kde-gtk-config
pacman -S --noconfirm kvantum
pacman -S --noconfirm libpulse
pacman -S --noconfirm libva-intel-driver
pacman -S --noconfirm linux
pacman -S --noconfirm linux-firmware
pacman -S --noconfirm mariadb
pacman -S --noconfirm mate-polkit
pacman -S --noconfirm matugen-bin
pacman -S --noconfirm meson
pacman -S --noconfirm mission-center
pacman -S --noconfirm mpd
pacman -S --noconfirm mtools
pacman -S --noconfirm nano
pacman -S --noconfirm nautilus
pacman -S --noconfirm neofetch
pacman -S --noconfirm neovim
pacman -S --noconfirm network-manager-applet
pacman -S --noconfirm niri
pacman -S --noconfirm nwg-look
pacman -S --noconfirm oh-my-posh
pacman -S --noconfirm os-prober
pacman -S --noconfirm otf-space-grotesk
pacman -S --noconfirm pipewire
pacman -S --noconfirm pipewire-alsa
pacman -S --noconfirm pipewire-jack
pacman -S --noconfirm pipewire-pulse
pacman -S --noconfirm plasma-browser-integration
pacman -S --noconfirm plymouth
pacman -S --noconfirm plymouth-theme-cubes-git
pacman -S --noconfirm pokemon-colorscripts-git
pacman -S --noconfirm pyright
pacman -S --noconfirm python-evdev
pacman -S --noconfirm python-loguru
pacman -S --noconfirm python-pip
pacman -S --noconfirm python-pipx
pacman -S --noconfirm python-pynvim
pacman -S --noconfirm python-pywal16
pacman -S --noconfirm python-pywalfox
pacman -S --noconfirm python311
pacman -S --noconfirm qt6-avif-image-plugin
pacman -S --noconfirm qt6-multimedia-ffmpeg
pacman -S --noconfirm qt6ct
pacman -S --noconfirm rmpc
pacman -S --noconfirm rofi
pacman -S --noconfirm sassc
pacman -S --noconfirm sddm
pacman -S --noconfirm sddm-silent-theme
pacman -S --noconfirm smartmontools
pacman -S --noconfirm sof-firmware
pacman -S --noconfirm speech-dispatcher
pacman -S --noconfirm spotify-launcher
pacman -S --noconfirm stow
pacman -S --noconfirm swayidle
pacman -S --noconfirm swaync
pacman -S --noconfirm swww
pacman -S --noconfirm sxiv
pacman -S --noconfirm timidity++
pacman -S --noconfirm ttf-dejavu
pacman -S --noconfirm ttf-fira-code
pacman -S --noconfirm ttf-fira-sans
pacman -S --noconfirm ttf-firacode-nerd
pacman -S --noconfirm ttf-liberation
pacman -S --noconfirm ttf-nerd-fonts-symbols
pacman -S --noconfirm ttf-rubik-vf
pacman -S --noconfirm ttf-twemoji
pacman -S --noconfirm tty-clock
pacman -S --noconfirm unzip
pacman -S --noconfirm uwsm
pacman -S --noconfirm vencord-bin
pacman -S --noconfirm vim
pacman -S --noconfirm vulkan-intel
pacman -S --noconfirm vulkan-nouveau
pacman -S --noconfirm vulkan-radeon
pacman -S --noconfirm waybar
pacman -S --noconfirm whitesur-icon-theme-git
pacman -S --noconfirm wireless_tools
pacman -S --noconfirm woff2-font-awesome
pacman -S --noconfirm wofi
pacman -S --noconfirm xdg-desktop-portal-gnome
pacman -S --noconfirm xdg-utils
pacman -S --noconfirm xf86-video-amdgpu
pacman -S --noconfirm xf86-video-ati
pacman -S --noconfirm xf86-video-nouveau
pacman -S --noconfirm xorg-server
pacman -S --noconfirm xorg-xinit
pacman -S --noconfirm xwayland-satellite
pacman -S --noconfirm yay
pacman -S --noconfirm yt-x
pacman -S --noconfirm zen-browser-bin
pacman -S --noconfirm zoxide
pacman -S --noconfirm zram-generator
pacman -S --noconfirm zsh
pacman -S --noconfirm zsh-autosuggestions
pacman -S --noconfirm zsh-completions
pacman -S --noconfirm zsh-syntax-highlighting
